ExamenPractico/Models/Filtrado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExamenPractico.Models
{
    public class Filtrado
    {
        public string TipoBusqueda { get; set; }
        public string FiltroDia { get; set; }
        public string FiltroMes { get; set; }
    }
}

ExamenPractico/Models/Pizza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExamenPractico.Models
{
    public class Pizza
    {
        public string Tamanio { get; set; }
        public string Ingredientes { get;set; }
        public int NumeroPizza { get; set; }
        public double Subtotal { get; set; }
        public double Result { get; set; }
        public double PrecioChica { get; set; }
        public double PrecioMediana { get; set; }
        public double PrecioGrande { get; set; }
        public double PrecioIngrediente { get; set; }
        public double Total { get; set; }
        public List<string> TodosIngrediente { get; set; }
        public string Pina { get; set; }
        public string Jamon { get; set; }
        public string Champinion { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
     


    }

    public class Persona
    {
        public string Nombre { get; set; }
        public DateTime Fecha { get; set; }
        public double Subtotal { get; set; }
        public double Total { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
    }
}

ExamenPractico/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenPractico.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ExamenPractico/Controllers/PizzaController.cs
using ExamenPractico.Models;
using ExamenPractico.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamenPractico.Controllers
{
    public class PizzaController : Controller
    {
        // GET: Pizza
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Pedidos()
        {
      
         
            return View();
        }

        [HttpPost]
        public ActionResult Pedidos(Pizza p)
        {
            
            var ope = new ServicePizza();
            p.TodosIngrediente = new List<string>();
            ope.GuardarArchivoPedido(p);
            var tabla = ope.LeerArchivoPedidos();
            ViewBag.tablaPedidos = tabla;
         

            return View(p);
        }


        public ActionResult DetallePedido()
        {
            var arch = new ServicePizza();
            var p = new Persona();
            
            ViewBag.Nombre = p.Nombre;
            ViewBag.Fecha = p.Fecha;
            ViewBag.Total = arch.TotalPrecioDetalle();
            ViewBag.temp = arch.LeerArchivoDetallesPedidos();
            return View();

        }

     

        public ActionResult Clientes()
        {
            var regis = new ServicePizza();
            ViewBag.tablaCliente = regis.LeerArchivoPersonas();
            ViewBag.Totalidad = regis.TotalPedidosClientes();
            return View();
        }

        [HttpPost]
        public ActionResult Clientes(String per)
        {
            var regis = new ServicePizza();
            bool s = false;
            if (per.Equals("lunes") || per.Equals("martes") || per.Equals("miércoles") || per.Equals("jueves") || per.Equals("viernes") || per.Equals("sábado") || per.Equals("domingo"))
            {
                s = true;
                ViewBag.tablaCliente = regis.DiasSemana(per, s);
                ViewBag.Totalidad = regis.TodoElFiltrado(per, s);
            }
            else if (per.Equals("enero") || per.Equals("febrero") || per.Equals("marzo") || per.Equals("abril") || per.Equals("mayo") || per.Equals("junio") || per.Equals("julio") || per.Equals("agosto") || per.Equals("septiembre") || per.Equals("octubre") || per.Equals("noviembre") || per.Equals("diciembre"))
            {
                ViewBag.tablaCliente = regis.DiasSemana(per, s);
                ViewBag.Totalidad = regis.TodoElFiltrado(per, s);
            }
            else
            {
                ViewBag.tablaCliente = null;
                ViewBag.Totalidad = 0;
            }
            return View();
            
        }

        public ActionResult Mensaje(Persona per)
        {
            var obj = new ServicePizza();
            obj.GuardarArchivoPersona(per);
            ViewBag.or = obj.BorrarPedidos(obj.LeerArchivoPedidos());
            return View();
        }

        public ActionResult MensajeImpreso()
        {
            var obj = new ServicePizza();
            obj.BorrarDetallesPedidos();

            return View();


        }


        public ActionResult Filtrado()
        {

            return View();
        }

     
    }
}

ExamenPractico/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ExamenPractico/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ExamenPractico/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ExamenPractico/Views/Pizza/Clientes.cshtml
@model ExamenPractico.Models.Pizza
@{
    ViewBag.Title = "Clientes";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ventas</title>
</head>
<body>
    <h1>Listado de ventas</h1>
    <div class=" row">
        <div class="col-sm-6">
            <form action="/Pizza/Clientes" method="post">
                <div class="row">
                    <div class="col-sm-12">
                        <select class="form-control" name="per">
                            <option>Selecciona...</option>
                            <option value="lunes">Lunes</option>
                            <option value="martes">Martes</option>
                            <option value="miércoles">Miercoles</option>
                            <option value="jueves">Jueves</option>
                            <option value="viernes">Viernes</option>
                            <option value="sábado">Sabado</option>
                            <option value="domingo">Domingo</option>
                        </select>
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-success" name="name" value=""> Día de la semana </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-6">
            <form action="/Pizza/Clientes" method="post">
                <div class="row">
                    <div class="">
                        <select class="form-control" name="per">
                            <option>Selecciona...</option>
                            <option value="enero">Enero</option>
                            <option value="febrero">Febrero</option>
                            <option value="marzo">Marzo</option>
                            <option value="abril">Abril</option>
                            <option value="mayo">Mayo</option>
                            <option value="junio">Junio</option>
                            <option value="julio">Julio</option>
                            <option value="agosto">Agosto</option>
                            <option value="septiembre">Septiembre</option>
                            <option value="octubre">Octubre</option>
                            <option value="noviembre">Noviembre</option>
                            <option value="diciembre">Diciembre</option>
                        </select>
                    </div>
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success" name="name" value="">Buscar por mes</button>
                    </div>
                </div>
            </form>
        </div>
      
    </div>
    <br />
    <div class="col">
        <table class=" table table-hover table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Fecha</th>
                    <th>Direccion</th>
                    <th>Telefono</th>
                    <th>Sub-Total</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.tablaCliente == null)
                {

                    <tr>
                       
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                }
                else
                {

                    foreach (var item in ViewBag.tablaCliente)
                    {
                        <tr>
                            @foreach (var registro in item.Split(','))
                            {
                                <td>@registro</td>
                            }
                        </tr>
                    }
                }

            </tbody>

            <tr>
                   <td></td>
                <td></td>
                <td></td>
                <td>Total :</td>
                <td>$ @ViewBag.Totalidad</td>
            </tr>
        </table>
    </div>
</body>
</html>

ExamenPractico/Views/Pizza/DetallePedido.cshtml
@model ExamenPractico.Models.Pizza

@{
    ViewBag.Title = "DetallePedido";
}

<h2>DetallePedido</h2>
<h2>@ViewBag.Nombre</h2>
<div class="container-fluid">
    <div class="row">
        <div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>Tamaño</td>
                        <td>Ingrediente</td>
                        <td>Numero de Pizzas</td>
                        <td>Subtotal</td>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.temp == null)
                    {

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                    else
                    {

                        foreach (var item in ViewBag.temp)
                        {
                            <tr>
                                @foreach (var registro in item.Split(','))
                                {
                                    <td>@registro</td>
                                }
                            </tr>
                        }
                    }
                <tr>
                    <td></td>
                    <td></td>
                    <td>Total: </td>
                    <td> $ @ViewBag.Total</td>
                  
                </tr>
                </tbody>
            </table>
            <form method="post" action="@Url.Action("MensajeImpreso","Pizza")">
                <button class="btn btn-primary" type="submit">Imprimir</button>
            </form>
        </div>
    </div>
</div>

ExamenPractico/Views/Pizza/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Ventana Principal</h2>

ExamenPractico/Views/Pizza/Mensaje.cshtml
@{
    ViewBag.Title = "Mensaje";
}

<h2>Mensaje</h2>

<h1>Registro existoso</h1>

ExamenPractico/Views/Pizza/MensajeImpreso.cshtml
@model ExamenPractico.Models.Pizza

@{
    ViewBag.Title = "MensajeImpreso";
}

<h2>Impresión Exitosa</h2>

ExamenPractico/Views/Pizza/Pedidos.cshtml
@model ExamenPractico.Models.Pizza
@{
    ViewBag.Title = "Pedidos";
}


<h2>Pedidos</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="">
                <div class="">
                    <form method="post" action="/Pizza/Pedidos">
                        <div class="form-group">
                      
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group " style="text-align: left; ">
                                        <div>
                                            <label class="" for="Tamanio">Tamaño de Pizza</label>
                                        </div>
                                        <div>
                                            <label>Chica $40</label> <input id="rt" name="Tamanio" type="radio" value="Chica" class="radio-inline" checked>
                                        </div>

                                        <div>
                                            <label>Mediana $80</label> <input id="rt" name="Tamanio" type="radio" value="Mediana" class="radio-inline">
                                        </div>

                                        <div>
                                            <label>Grande $120</label> <input id="rt" name="Tamanio" type="radio" value="Grande" class="radio-inline">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="form-group " style="text-align: left; ">
                                        <div>
                                            <label class="" for="">Ingredientes</label>
                                        </div>
                                        <div>
                                            <label>Jamon $10</label> <input id="" name="Jamon" type="checkbox" value="Jamon" class="form-check-input" checked>

                                        </div>
                                        <div>
                                            <label>Piña $10</label> <input id="" name="Pina" type="checkbox" value="Piña" class="form-check-input">
                                        </div>
                                        <div>
                                            <label>Chapiñones $10</label> <input id="" name="Champinion" type="checkbox" value="Champiñon" class="form-check-input">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="form-group " style="text-align: left; ">
                                        <label for="NumeroPizza">Número de Pizzas</label>
                                        <input id="Numero" name="NumeroPizza" maxlength="40" type="number" value="" class="form-control" required min="1">
                                        <div class="" style="margin-top: 15px">
                                            <button class="btn btn-warning" type="submit" name="btnAgregar">Agregar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>Tamaño</td>
                        <td>Ingrediente</td>
                        <td>Numero de Pizzas</td>
                        <td>Subtotal</td>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.tablaPedidos == null)
                    {

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    }
                    else
                    {

                        foreach (var item in ViewBag.tablaPedidos)
                        {
                            <tr>
                                @foreach (var registro in item.Split(','))
                                {
                                    <td>@registro</td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div class="">
                <form method="post" action="@Url.Action("Mensaje","Pizza")">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group col-md-12" style="text-align: left; ">
                                <label for="Nombre">Nombre</label>
                                <input id="Nombretxt" name="Nombre" maxlength="40" type="text" value="" class="form-control" required >
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group " style="text-align: left; ">
                                <label for="Direccion">Dirección</label>
                                <input id="Direcciontxt" name="Domicilio" maxlength="40" type="text" value="" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group " style="text-align: left; ">
                                <label for="Telefono">Teléfono</label>
                                <input id="Telefonotxt" name="Telefono" maxlength="40" type="number" value="" class="form-control" required min="10">
                            </div>
                        </div>
                    </div>
                    <div class="" style="margin-top: 15px">
                        <button class="btn btn-warning" type="submit" name="btnTerminar">Terminar</button>
                    </div>
                </form>
            </div>
        
        </div>
    </div>

</div>

ExamenPractico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Incio", "Index", "Pizza")</li>
                    <li>@Html.ActionLink("Pedido", "Pedidos", "Pizza")</li>
                    <li>@Html.ActionLink("Detalle Pedido", "DetallePedido", "Pizza")</li>
                    <li>@Html.ActionLink("Clientes", "Clientes", "Pizza")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>